---
- name: Install a few python tools (needed for mysql)
  apt: name={{ item }} state=installed
  with_items:
    - python-dev
    - python-pip
    - python-setuptools
  become: true

- name: Install MySQL (and dependencies)
  apt: name={{ item }} state=installed
  with_items:
    - mysql-server
    - libapache2-mod-auth-mysql
    - libmysqlclient-dev
  become: true

- name: Install the MySQL-Python module
  pip: name=MySQL-python
  become: true

- name: Activate MySQL
  command: mysql_install_db
  become: true

- name: Secure MySQL - update MySQL root password for all root accounts
  mysql_user: name=root host={{ item }} password={{ mysql_root_password }}
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
  ignore_errors: yes
  become: true
  notify:
  - Restart mysql

- name: Secure MySQL - delete anonymous MySQL server user for {{ ansible_hostname }}
  action: mysql_user user="" host="{{ ansible_hostname }}" state="absent" login_user=root login_password={{ mysql_root_password }}
  become: true
  notify:
  - Restart mysql

- name: Secure MySQL - delete anonymous MySQL server user for localhost
  action: mysql_user user="" state="absent" login_user=root login_password={{ mysql_root_password }}
  become: true
  notify:
  - Restart mysql

- name: Secure MySQL - remove the MySQL test database
  action: mysql_db db=test state=absent login_user=root login_password={{ mysql_root_password }}
  become: true
  notify:
  - Restart mysql
